#!/usr/bin/env node
/**
 * Generates src/data/stateMLAs.js and src/data/stateMPs.js from the backend's
 * verified datasets (backend/src/data/state_mlas.json, state_voter_profiles.json),
 * so the frontend and backend rosters can never drift.
 *
 *   node frontend/scripts/gen_state_data.js
 *
 * Re-run after any change to the backend roster (by-election, defection,
 * reshuffle). Vacant seats are emitted with mla/party "Vacant" and
 * `vacant: true`, so every screen that prints them still renders.
 */
const fs = require('fs');
const path = require('path');

const DATA = path.join(__dirname, '..', '..', 'backend', 'src', 'data');
const OUT = path.join(__dirname, '..', 'src', 'data');

const mlas = JSON.parse(fs.readFileSync(path.join(DATA, 'state_mlas.json'), 'utf8'));
const aliases = JSON.parse(fs.readFileSync(path.join(DATA, 'state_constituency_aliases.json'), 'utf8')).aliases;
const GEO = JSON.parse(fs.readFileSync(path.join(DATA, 'state_geo.json'), 'utf8'));

// District list and every variant spelling (English aliases, Telugu name,
// "<name> district") → canonical name, lower-cased on both sides. Mirrors
// backend/src/config/stateLocations.js DISTRICT_VARIANTS.
const districtNames = GEO.districts.map((d) => d.name).sort((a, b) => a.localeCompare(b));
const districtAliases = {};
for (const d of GEO.districts) {
  for (const n of [d.name, d.telugu, ...(d.aliases || [])].filter(Boolean)) {
    const k = n.toLowerCase().replace(/[^a-z0-9\u0900-\u097F\s]/g, ' ').replace(/\s+/g, ' ').trim();
    districtAliases[k] = d.name.toLowerCase();
    if (/[a-z]/i.test(n)) districtAliases[`${k} district`] = d.name.toLowerCase();
  }
}

const rows = mlas.map((m) => ({
  acNumber: m.ac_number,
  constituency: m.constituency,
  key: m.key,
  district: m.district,
  // Elected BRS, sitting with Congress, disqualification petition dismissed
  // by the Speaker on 11 Mar 2026. Passed through so a screen can separate
  // the House's 36 BRS members from the 27 that are BRS in practice.
  defectedTo: m.defected_to || null,
  taluka: m.taluka,
  lokSabha: m.lok_sabha,
  reserved: m.reserved_category || null,
  mla: m.vacant ? 'Vacant' : m.mla,
  party: m.vacant ? 'Vacant' : m.party,
  alliance: m.vacant ? '—' : m.alliance,
  vacant: !!m.vacant,
  criminalCases: m.vacant ? null : m.criminalCases,
  education: m.vacant ? null : m.education,
  assets: m.vacant ? null : m.assets,
  liabilities: m.vacant ? null : m.liabilities,
}));

const tally = rows.reduce((acc, r) => { acc[r.party] = (acc[r.party] || 0) + 1; return acc; }, {});

const mlaModule = `// AUTO-GENERATED by frontend/scripts/gen_state_data.js from
// backend/src/data/state_mlas.json — do not edit by hand.
// Telangana Legislative Assembly, 119 seats. 2023 election affidavits (ADR;
// no affidavit for the two by-poll winners or the vacant seat); current party as of Sep 2026.
// Tally: ${Object.entries(tally).map(([p, n]) => `${p} ${n}`).join(', ')}.
//
// Each record: acNumber, constituency (ECI name), key (normalized lookup),
// district (current, 33 districts), taluka (tehsil), lokSabha, reserved, mla, party,
// alliance, vacant, criminalCases, education, assets, liabilities.

export const STATE_MLAS = ${JSON.stringify(rows, null, 2)};

export const normalizeConstituencyKey = (name) =>
  String(name || '')
    .normalize('NFD')
    .replace(/[\\u0300-\\u036f]/g, '')
    .toLowerCase()
    .replace(/\\([^)]*\\)/g, ' ')
    .replace(/[^a-z0-9]/g, '')
    .trim();

// Alternate spellings (Hindi / press spellings) → ECI key.
// From backend/src/data/state_constituency_aliases.json (shared with the backend).
const CONSTITUENCY_ALIASES = ${JSON.stringify(aliases, null, 2)};

export const MLA_BY_KEY = STATE_MLAS.reduce((acc, m) => {
  acc[m.key] = m;
  acc[normalizeConstituencyKey(m.constituency)] = m;
  return acc;
}, {});

export const getMlaByConstituency = (name) => {
  const k = normalizeConstituencyKey(name);
  return MLA_BY_KEY[k] || MLA_BY_KEY[CONSTITUENCY_ALIASES[k]] || null;
};

// The state's current districts, and their variant spellings (lower-case →
// canonical lower-case), from backend/src/data/state_geo.json.
export const STATE_DISTRICTS = ${JSON.stringify(districtNames, null, 2)};

export const DISTRICT_ALIASES = ${JSON.stringify(districtAliases, null, 2)};

const DISTRICT_DISPLAY = STATE_DISTRICTS.reduce((acc, d) => { acc[d.toLowerCase()] = d; return acc; }, {});
const districtLookupKey = (v) => String(v || '').toLowerCase().replace(/[^a-z0-9\u0900-\u097F\s]/g, ' ').replace(/\s+/g, ' ').trim();

/** Canonical district display name for any spelling ('' when unknown). */
export const canonicalDistrictName = (v) => {
  const k = districtLookupKey(v);
  return DISTRICT_DISPLAY[DISTRICT_ALIASES[k] || k] || '';
};

export default STATE_MLAS;
`;

// Lok Sabha MPs come from the backend roster, so the two cannot drift.
const { ALLY_MPS, OPPOSITION_MPS } = require('../../backend/src/config/politicalData');
const LS_TO_AC = JSON.parse(fs.readFileSync(path.join(DATA, 'state_ls_to_ac.json'), 'utf8'));
const ALLIANCE = { BJP: 'NDA', INC: 'INDIA' };
const lsKey = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]/g, '');
const mps = [...ALLY_MPS, ...OPPOSITION_MPS]
  .filter((m) => /lok sabha/i.test(m.role || ''))
  .map((m) => ({ lsId: lsKey(m.constituency), lsName: m.constituency, mp: m.name, party: m.party, alliance: ALLIANCE[m.party] || m.party }))
  .sort((a, b) => Object.keys(LS_TO_AC).indexOf(a.lsId) - Object.keys(LS_TO_AC).indexOf(b.lsId));
const missingLs = Object.keys(LS_TO_AC).filter((k) => !mps.some((m) => m.lsId === k));
if (missingLs.length) throw new Error(`No MP in the roster for Lok Sabha seat(s): ${missingLs.join(', ')}`);
const mpTally = mps.reduce((acc, m) => { acc[m.party] = (acc[m.party] || 0) + 1; return acc; }, {});

const mpModule = `// AUTO-GENERATED by frontend/scripts/gen_state_data.js — do not edit by hand.
// Telangana 2024 Lok Sabha results — ${mps.length} seats (${Object.entries(mpTally).map(([p, n]) => `${p} ${n}`).join(', ')}).
// Generated from backend/src/config/politicalData.js.
//
// \`lsId\` matches the keys of backend/src/data/state_ls_to_ac.json.

export const STATE_MPS = ${JSON.stringify(mps, null, 2)};

const normalize = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]/g, '');

export const MP_BY_LS_ID = STATE_MPS.reduce((acc, m) => {
  acc[m.lsId] = m;
  return acc;
}, {});

const MP_BY_LS_NAME = STATE_MPS.reduce((acc, m) => {
  acc[normalize(m.lsName)] = m;
  return acc;
}, {});

export const getMpByLsId = (lsId) => MP_BY_LS_ID[normalize(lsId)] || null;

export const getMpByLsName = (name) => MP_BY_LS_NAME[normalize(name)] || null;

export default STATE_MPS;
`;

fs.writeFileSync(path.join(OUT, 'stateMLAs.js'), mlaModule);
fs.writeFileSync(path.join(OUT, 'stateMPs.js'), mpModule);
console.log(`wrote stateMLAs.js (${rows.length} seats: ${JSON.stringify(tally)}) and stateMPs.js (${mps.length} seats)`);
